### ISSUE TITLE
CloudObjectStoreContainer warning and MissingRegionError

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/manageiq-providers-amazon#161]
Running on latest master with a refreshed database.

I spotted an error and a warning in the evm.log during an AWS refresh that may be of concern. Neither appears to affect the refresh, but they should probably be addressed.

The warning is: `warning: toplevel constant CloudObjectStoreContainer referenced by ManageIQ::Providers::Amazon::StorageManager::S3::CloudObjectStoreContainer`

The error is: `[Aws::Errors::MissingRegionError]: missing region; use :region option or export region name to ENV['AWS_REGION']  Method:[rescue in block in refresh]`

To duplicate, just add or refresh an AWS provider that contains resources. The full backtrace that I'm seeing is below:

```
[----] I, [2017-03-06T09:10:10.300053 #79505:3fc7d783fa0c]  INFO -- : MIQ(ManageIQ::Providers::Amazon::StorageManager::S3::Refresher#refresh_targets_for_ems) EMS: [amazon S3 Storage Manager], id: [8] Refreshing target ManageIQ::Providers::Amazon::StorageManager::S3 [amazon S3 Storage Manager] id [8]...
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-amazon-b65b8993449b/app/models/manageiq/providers/amazon/inventory/parser/storage_manager/s3.rb:80: warning: toplevel constant CloudObjectStoreContainer referenced by ManageIQ::Providers::Amazon::StorageManager::S3::CloudObjectStoreContainer
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-amazon-b65b8993449b/app/models/manageiq/providers/amazon/inventory/parser/storage_manager/s3.rb:80: warning: toplevel constant CloudObjectStoreContainer referenced by ManageIQ::Providers::Amazon::StorageManager::S3::CloudObjectStoreContainer
[----] E, [2017-03-06T09:10:11.343181 #79505:3fc7d783fa0c] ERROR -- : MIQ(ManageIQ::Providers::Amazon::StorageManager::S3::Refresher#refresh) EMS: [amazon S3 Storage Manager], id: [8] Refresh failed
[----] E, [2017-03-06T09:10:11.343482 #79505:3fc7d783fa0c] ERROR -- : [Aws::Errors::MissingRegionError]: missing region; use :region option or export region name to ENV['AWS_REGION']  Method:[rescue in block in refresh]
[----] E, [2017-03-06T09:10:11.343706 #79505:3fc7d783fa0c] ERROR -- : /Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.50/lib/aws-sdk-core/plugins/regional_endpoint.rb:34:in `after_initialize'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.50/lib/seahorse/client/base.rb:84:in `block in after_initialize'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.50/lib/seahorse/client/base.rb:83:in `each'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.50/lib/seahorse/client/base.rb:83:in `after_initialize'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.50/lib/seahorse/client/base.rb:21:in `initialize'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.50/lib/seahorse/client/base.rb:105:in `new'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.6.50/lib/aws-sdk-resources/resource.rb:169:in `extract_client'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.6.50/lib/aws-sdk-resources/resource.rb:15:in `initialize'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-amazon-b65b8993449b/app/models/manageiq/providers/amazon/manager_mixin.rb:72:in `new'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-amazon-b65b8993449b/app/models/manageiq/providers/amazon/manager_mixin.rb:72:in `raw_connect'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-amazon-b65b8993449b/app/models/manageiq/providers/amazon/manager_mixin.rb:29:in `connect'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-amazon-b65b8993449b/app/models/manageiq/providers/amazon/storage_manager/s3.rb:37:in `connect'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-amazon-b65b8993449b/app/models/manageiq/providers/amazon/inventory/collector/storage_manager/s3.rb:27:in `aws_s3_regional'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-amazon-b65b8993449b/app/models/manageiq/providers/amazon/inventory/collector/storage_manager/s3.rb:11:in `cloud_object_store_objects'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-amazon-b65b8993449b/app/models/manageiq/providers/amazon/inventory/parser/storage_manager/s3.rb:49:in `process_objects'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-amazon-b65b8993449b/app/models/manageiq/providers/amazon/inventory/parser/storage_manager/s3.rb:23:in `block in process_containers'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-amazon-b65b8993449b/app/models/manageiq/providers/amazon/inventory/parser/storage_manager/s3.rb:21:in `each'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-amazon-b65b8993449b/app/models/manageiq/providers/amazon/inventory/parser/storage_manager/s3.rb:21:in `process_containers'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-amazon-b65b8993449b/app/models/manageiq/providers/amazon/inventory/parser/storage_manager/s3.rb:10:in `parse'
/Users/dberger/Repositories/manageiq-djberg96/app/models/manager_refresh/inventory.rb:23:in `block in inventory_collections'
/Users/dberger/Repositories/manageiq-djberg96/app/models/manager_refresh/inventory.rb:20:in `each'
/Users/dberger/Repositories/manageiq-djberg96/app/models/manager_refresh/inventory.rb:20:in `inventory_collections'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-amazon-b65b8993449b/app/models/manageiq/providers/amazon/storage_manager/s3/refresher.rb:27:in `block in parse_targeted_inventory'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-fae141b817f2/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-fae141b817f2/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-amazon-b65b8993449b/app/models/manageiq/providers/amazon/storage_manager/s3/refresher.rb:25:in `parse_targeted_inventory'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:87:in `block in refresh_targets_for_ems'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-fae141b817f2/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-fae141b817f2/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:86:in `refresh_targets_for_ems'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:24:in `block (2 levels) in refresh'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-fae141b817f2/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-fae141b817f2/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:24:in `block in refresh'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:14:in `each'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:14:in `refresh'
/Users/dberger/Repositories/manageiq-djberg96/app/models/manageiq/providers/base_manager/refresher.rb:10:in `refresh'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh.rb:93:in `block in refresh'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh.rb:92:in `each'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh.rb:92:in `refresh'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue.rb:347:in `block in deliver'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue.rb:343:in `deliver'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue_worker_base/runner.rb:106:in `deliver_queue_message'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue_worker_base/runner.rb:134:in `deliver_message'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue_worker_base/runner.rb:152:in `block in do_work'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue_worker_base/runner.rb:146:in `loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue_worker_base/runner.rb:146:in `do_work'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:334:in `block in do_work_loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:331:in `loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:331:in `do_work_loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:153:in `run'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:128:in `start'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:21:in `start_worker'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker.rb:343:in `block in start_runner'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nakayoshi_fork-0.0.3/lib/nakayoshi_fork.rb:24:in `fork'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nakayoshi_fork-0.0.3/lib/nakayoshi_fork.rb:24:in `fork'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker.rb:341:in `start_runner'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker.rb:352:in `start'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker.rb:270:in `start_worker'
/Users/dberger/Repositories/manageiq-djberg96/app/models/mixins/per_ems_worker_mixin.rb:68:in `start_worker_for_ems'
/Users/dberger/Repositories/manageiq-djberg96/app/models/mixins/per_ems_worker_mixin.rb:46:in `block in sync_workers'
/Users/dberger/Repositories/manageiq-djberg96/app/models/mixins/per_ems_worker_mixin.rb:45:in `each'
/Users/dberger/Repositories/manageiq-djberg96/app/models/mixins/per_ems_worker_mixin.rb:45:in `sync_workers'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server/worker_management/monitor.rb:53:in `block in sync_workers'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server/worker_management/monitor.rb:50:in `each'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server/worker_management/monitor.rb:50:in `sync_workers'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server/worker_management/monitor.rb:22:in `monitor_workers'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:348:in `block in monitor'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-fae141b817f2/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-fae141b817f2/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:348:in `monitor'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:370:in `block (2 levels) in monitor_loop'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-fae141b817f2/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-fae141b817f2/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:370:in `block in monitor_loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:369:in `loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:369:in `monitor_loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:252:in `start'
/Users/dberger/Repositories/manageiq-djberg96/lib/workers/evm_server.rb:65:in `start'
/Users/dberger/Repositories/manageiq-djberg96/lib/workers/evm_server.rb:91:in `start'
/Users/dberger/Repositories/manageiq-djberg96/lib/workers/bin/evm_server.rb:4:in `<main>'
[----] E, [2017-03-06T09:10:11.343815 #79505:3fc7d783fa0c] ERROR -- : MIQ(ManageIQ::Providers::Amazon::StorageManager::S3::Refresher#refresh) EMS: [amazon S3 Storage Manager], id: [8] Unable to perform refresh for the following targets:
[----] E, [2017-03-06T09:10:11.343939 #79505:3fc7d783fa0c] ERROR -- : MIQ(ManageIQ::Providers::Amazon::StorageManager::S3::Refresher#refresh)  --- ManageIQ::Providers::Amazon::StorageManager::S3 [amazon S3 Storage Manager] id [8]
[----] I, [2017-03-06T09:10:11.414577 #79505:3fc7d783fa0c]  INFO -- : MIQ(ManageIQ::Providers::Amazon::StorageManager::S3::Refresher#refresh) Refreshing all targets...Complete
[----] E, [2017-03-06T09:10:11.414792 #79505:3fc7d783fa0c] ERROR -- : MIQ(MiqQueue#deliver) Message id: [25761], Error: [missing region; use :region option or export region name to ENV['AWS_REGION']]
[----] E, [2017-03-06T09:10:11.414962 #79505:3fc7d783fa0c] ERROR -- : [EmsRefresh::Refreshers::EmsRefresherMixin::PartialRefreshError]: missing region; use :region option or export region name to ENV['AWS_REGION']  Method:[rescue in deliver]
[----] E, [2017-03-06T09:10:11.415119 #79505:3fc7d783fa0c] ERROR -- : /Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:50:in `refresh'
/Users/dberger/Repositories/manageiq-djberg96/app/models/manageiq/providers/base_manager/refresher.rb:10:in `refresh'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh.rb:93:in `block in refresh'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh.rb:92:in `each'
/Users/dberger/Repositories/manageiq-djberg96/app/models/ems_refresh.rb:92:in `refresh'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue.rb:347:in `block in deliver'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue.rb:343:in `deliver'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue_worker_base/runner.rb:106:in `deliver_queue_message'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue_worker_base/runner.rb:134:in `deliver_message'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue_worker_base/runner.rb:152:in `block in do_work'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue_worker_base/runner.rb:146:in `loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_queue_worker_base/runner.rb:146:in `do_work'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:334:in `block in do_work_loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:331:in `loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:331:in `do_work_loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:153:in `run'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:128:in `start'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker/runner.rb:21:in `start_worker'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker.rb:343:in `block in start_runner'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nakayoshi_fork-0.0.3/lib/nakayoshi_fork.rb:24:in `fork'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nakayoshi_fork-0.0.3/lib/nakayoshi_fork.rb:24:in `fork'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker.rb:341:in `start_runner'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker.rb:352:in `start'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_worker.rb:270:in `start_worker'
/Users/dberger/Repositories/manageiq-djberg96/app/models/mixins/per_ems_worker_mixin.rb:68:in `start_worker_for_ems'
/Users/dberger/Repositories/manageiq-djberg96/app/models/mixins/per_ems_worker_mixin.rb:46:in `block in sync_workers'
/Users/dberger/Repositories/manageiq-djberg96/app/models/mixins/per_ems_worker_mixin.rb:45:in `each'
/Users/dberger/Repositories/manageiq-djberg96/app/models/mixins/per_ems_worker_mixin.rb:45:in `sync_workers'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server/worker_management/monitor.rb:53:in `block in sync_workers'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server/worker_management/monitor.rb:50:in `each'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server/worker_management/monitor.rb:50:in `sync_workers'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server/worker_management/monitor.rb:22:in `monitor_workers'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:348:in `block in monitor'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-fae141b817f2/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-fae141b817f2/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:348:in `monitor'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:370:in `block (2 levels) in monitor_loop'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-fae141b817f2/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/Users/dberger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-fae141b817f2/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:370:in `block in monitor_loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:369:in `loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:369:in `monitor_loop'
/Users/dberger/Repositories/manageiq-djberg96/app/models/miq_server.rb:252:in `start'
/Users/dberger/Repositories/manageiq-djberg96/lib/workers/evm_server.rb:65:in `start'
/Users/dberger/Repositories/manageiq-djberg96/lib/workers/evm_server.rb:91:in `start'
/Users/dberger/Repositories/manageiq-djberg96/lib/workers/bin/evm_server.rb:4:in `<main>'
[----] I, [2017-03-06T09:10:11.415274 #79505:3fc7d783fa0c]  INFO -- : MIQ(MiqQueue#delivered) Message id: [25761], State: [error], Delivered in [1.44828] seconds
[----] I, [2017-03-06T09:10:12.183275 #79502:3fc7d783fa0c]  INFO -- : MIQ(EmsRefresh.save_ems_block_storage_inventory) EMS: [amazon EBS Storage Manager], id: [7] Saving EMS Inventory...
Session:	 Hash of Size 7089, Elements 29
```

**Comment by bronaghs** [comment]
@miha-plesko @gberginc - can you take a look, thanks.

**Comment by Fryguy** [comment]
toplevel constant error means that you tried to fully qualify a reference to a class `ManageIQ::Providers::Amazon::StorageManager::S3::CloudObjectStoreContainer`, but that class doesn't exist in that namespace.  Instead it was loaded via the toplevel constant.  You have to create `ManageIQ::Providers::Amazon::StorageManager::S3::CloudObjectStoreContainer`, or if you intended to use the toplevel constant, then you should just call it that way.

**Comment by miha-plesko** [comment]
Thank you @djberg96, I will take a look when I come to the office.

**Comment by miha-plesko** [comment]
@djberg96 Issue with warnings has been resolved with this PR (already merged): https://github.com/ManageIQ/manageiq-providers-amazon/pull/166

But I'm having hard time reproducing the Region error that you've described above. Please let me know if you do it same as I do:

1 recreate database
`bin/rake db:drop db:create db:migrate`

2 start server
`MIQ_SPARTAN=minimal:ems_inventory rake evm:start`

3 add a new cloud provider
![capture](https://cloud.githubusercontent.com/assets/8102426/23658818/2f045024-0344-11e7-8a30-abc737afd356.PNG)

4 wait a minute or two until refresh is done

There are no errors in my evm.log nor aws.log after step 4 and I'm not sure why you have them. I will play with it some more, but if you have some additional information (e.g. what region are you connecting to), I'd be glad to know.

Thank again for testing this.

**Comment by djberg96** [comment]
@miha-plesko I did a bin/setup on the latest master and selected "US East (Northern Virginia)" as my region. I still see the error.

One thing I did remember is that I have $HOME/.aws/config with the following options:
```
[default]
output = json
region = us-east-1
```
I'm pretty sure I set that up for the command line tool. Could this be the source of the problem? And if so, is this something we should handle?

I double checked my .bash_profile, but did not see any specific ENV variables set there for AWS.

**Comment by djberg96** [comment]
Just a quick update, I commented out the region option, and did a `bundle exec rake evm:restart`. I'm still seeing the error, though.

**Comment by miha-plesko** [comment]
@djberg96 i just managed to reproduce the error. Turns out that SDK call `get_bucket_location` returns region string for every region but Northern Virginia. Northern Virginia is considered as default, therefore the SDK call simply returns `""` (empty string) 😄, hence the error.

Let me prepare PR to fix it, I'll let you know when it's merged. Thank you so much for finding this out - we wouldn't want to notice it after release ;)

**Comment by miha-plesko** [comment]
@djberg96 @bronaghs The PR that should resolve the error described here is merged. The inventory should now be collected without any problems.

Paying more attention to how S3 works with regions it turned out that operations on bucket (delete bucket, clear bucket, delete object) require different SDK connection to be established depending on region where bucket exists. This is quite surprising for me since S3 is "region agnostic", but whatever. Until I handle this properly, operations on buckets will only work for buckets that are within the same region as EC2 cloud manager. Please have this in mind until tomorrow (should you be testing), when I prepare PR to fix it.

**Comment by djberg96** [comment]
I'll go ahead and close this, as the original problem has been solved. I'm glad that I reported it since it led to discovering the bucket issue as well. :)
